name: MERN Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install and build backend
        run: |
          cd backend
          npm install
          npm run build || echo "No backend build script"

      - name: Install and build frontend
        run: |
          cd frontend
          npm install
          npm run build
