name: MERN Basic Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install backend dependencies and test
      run: |
        cd backend
        npm install
        npm test || echo "No backend tests"

    - name: Install frontend dependencies and test
      run: |
        cd frontend
        npm install
        npm test || echo "No frontend tests"
